### ISSUE TITLE
Arrumar readme e github pages

### ISSUE THREAD

**Issue by Wengel-Rodrigues** [Requisitos-de-Software/2022.2-FifaPlus#20]

**Comment by Eric-chagas** [comment]
Ajustadas todas as legendas, conteúdo das páginas e readme de acordo com o novo aplicativo. 

### PADRÃO SEGUIDO PRAS LEGENDAS (IMPORTANTE)

Heading 6 do markdown, no seguinte formato (exemplo de figura): `###### Figura X - Descrição. Fonte: Autoria própria (ou fonte externa)`
